version: '3'

services:
  docker_springboot_kotlin_demo:
    depends_on:
      - postgres_database
    image: docker_springboot_kotlin_demo
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2222:8090"
    container_name: docker_springboot_kotlin_demo
  postgres_database:
    image: postgres:13.3-buster
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "/c/docker/postgres:/var/lib/postgresql/data"
    ports:
      - "1111:5432"
    container_name: postgres_database